#pragma once

#include "csf/tree.hpp"

#include <cstdint>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace csf {

// Engine semantics recovered statically from CommXPC.exe (format-reversal
// KB-scripting-31/34/39), joined onto a row by opcode head name from
// tools/script_semantics.tsv. The default values mean "no semantics attached":
// the table is generated without them when --semantics is not passed.
struct ScriptSemantics {
    std::int32_t vm_mode{-1};       // vm+0x18 value; -1 = not a driver-mode setter
    std::int32_t order_tag{-1};     // ScriptOrder tag; -1 = no order command
    bool wait{false};               // vm+0x60/0x64 + vm+0x82 wait wrapper
    std::uint16_t opcode_id{};      // 0xffff = no registry entry
    std::uint32_t handler{};        // dispatch handler; 0 = inline/unknown
    bool confirmed{false};          // false = semantics fields not analysed
    std::string_view operand_kinds; // registry operand-kind ids, ';'-separated
};

// Observed shape of one script instruction or operand head in the shipped
// programs (generated by tools/generate_script_signatures.py).
struct ScriptSignature {
    std::string_view head;
    bool instruction{};
    std::uint8_t minimum_arity{};
    std::uint8_t maximum_arity{};
    std::uint32_t uses{};
    // One entry per argument position, separated by ';'. Each entry lists the
    // shapes seen there, separated by '|': an operand tag, or one of
    // int, real, string, group and array.
    std::string_view positions;
    // Additive engine semantics; default-constructed when the table was
    // generated without --semantics.
    ScriptSemantics semantics{};
};

[[nodiscard]] std::span<const ScriptSignature> script_signatures() noexcept;
[[nodiscard]] const ScriptSignature* find_script_signature(std::string_view head,
                                                           bool instruction) noexcept;

struct ScriptCheck {
    std::string message;
    std::string opcode;
};

// Compares a script record (or an instruction list) with the signature table.
// Every finding is advisory: it means that the shipped game data never uses the
// construct, not that the engine rejects it.
[[nodiscard]] std::vector<ScriptCheck> check_script_against_signatures(const TreeNode& node);

} // namespace csf
