#pragma once

#include "csf/tree.hpp"

#include <cstdint>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace csf {

// Observed shape of one script instruction or operand head in the shipped
// programs (generated by tools/generate_script_signatures.py).
struct ScriptSignature {
    std::string_view head;
    bool instruction{};
    std::uint8_t minimum_arity{};
    std::uint8_t maximum_arity{};
    std::uint32_t uses{};
    // One entry per argument position, separated by ';'. Each entry lists the
    // shapes seen there, separated by '|': an operand tag, or one of
    // int, real, string, group and array.
    std::string_view positions;
};

[[nodiscard]] std::span<const ScriptSignature> script_signatures() noexcept;
[[nodiscard]] const ScriptSignature* find_script_signature(std::string_view head,
                                                           bool instruction) noexcept;

struct ScriptCheck {
    std::string message;
    std::string opcode;
};

// Compares a script record (or an instruction list) with the signature table.
// Every finding is advisory: it means that the shipped game data never uses the
// construct, not that the engine rejects it.
[[nodiscard]] std::vector<ScriptCheck> check_script_against_signatures(const TreeNode& node);

} // namespace csf
