#include "ui/fonts.hpp"

#include "ui/icons.hpp"
#include "ui/theme.hpp"

#include <GLFW/glfw3.h>
#include <imgui_impl_opengl3.h>

#include <algorithm>
#include <cmath>

namespace rwsman::ui {
namespace {

// Generated by tools/generate_ui_fonts.py.
#include "ui/fonts/inter_regular.inc"
#include "ui/fonts/inter_semibold.inc"
#include "ui/fonts/iosevka_term_regular.inc"
#include "ui/fonts/lucide_subset.inc"

// Sizes at 100% UI scale. IosevkaTerm is narrow, so it matches Inter's line
// height at the same size while fitting more hex and IDs per column. The type
// scale (docs/archive/editor/editor-ux-redesign.md, V2) is caption, body (and the bold
// body for headings) and title.
constexpr float sans_size = 15.0F;
constexpr float mono_size = 14.0F;
constexpr float icon_size = 14.0F;
constexpr float title_size = 24.0F;
constexpr float caption_size = 13.0F;

ImFont* fonts[5]{};
float applied_os_scale = 0.0F, applied_framebuffer_scale = 0.0F, applied_user_scale = 0.0F;
float current_scale = 1.0F;

ImFont* add_text_font(ImGuiIO& io, const char* base85, const float pixels) {
    ImFontConfig config;
    config.OversampleH = 2;
    config.OversampleV = 1;
    config.FontDataOwnedByAtlas = true;
    static const ImWchar ranges[] = {0x0020, 0x00FF, 0x0100, 0x017F, 0x2010, 0x203A, 0x20AC, 0x20AC,
                                     0x2190, 0x2193, 0x2212, 0x2212, 0x2264, 0x2265, 0x25A0, 0x25CF,
                                     0x2713, 0x2714, 0};
    return io.Fonts->AddFontFromMemoryCompressedBase85TTF(base85, pixels, &config, ranges);
}

void merge_icons(ImGuiIO& io, const float pixels) {
    ImFontConfig config;
    config.MergeMode = true;
    config.PixelSnapH = true;
    config.GlyphMinAdvanceX = pixels + 2.0F;
    config.GlyphOffset = {0.0F, 1.0F};
    io.Fonts->AddFontFromMemoryCompressedBase85TTF(lucide_subset_compressed_data_base85, pixels,
                                                   &config, icons::glyph_ranges);
}

} // namespace

ImFont* font(const Font which) {
    return fonts[static_cast<int>(which)];
}

float ui_scale() {
    return current_scale;
}

bool update_fonts_and_style(GLFWwindow* window, const float user_scale) {
    int window_width = 0, window_height = 0, framebuffer_width = 0, framebuffer_height = 0;
    glfwGetWindowSize(window, &window_width, &window_height);
    glfwGetFramebufferSize(window, &framebuffer_width, &framebuffer_height);
    float content_x = 1.0F, content_y = 1.0F;
    glfwGetWindowContentScale(window, &content_x, &content_y);

    // Some platforms (macOS, Wayland) scale the window itself and expose the
    // extra pixels only in the framebuffer; others (Windows, X11) keep window
    // and framebuffer pixels equal and report the scale as a content scale.
    // ImGui works in window units, so only the part of the content scale that
    // the OS has not already applied to the window is ours to apply.
    const float framebuffer_scale =
        window_width > 0 ? static_cast<float>(framebuffer_width) / static_cast<float>(window_width)
                         : 1.0F;
    const float content_scale = std::max(content_x, content_y);
    const float os_scale = std::clamp(content_scale / std::max(framebuffer_scale, 1.0F), 1.0F, 4.0F);
    const float fb_scale = std::max(framebuffer_scale, 1.0F);
    const float user = std::clamp(user_scale, 0.8F, 2.0F);

    const auto same = [](const float a, const float b) { return std::fabs(a - b) < 0.001F; };
    if (fonts[0] != nullptr && same(os_scale, applied_os_scale) &&
        same(fb_scale, applied_framebuffer_scale) && same(user, applied_user_scale))
        return false;

    auto& io = ImGui::GetIO();
    const bool first = fonts[0] == nullptr;
    io.Fonts->Clear();
    const float scale = os_scale * user;
    // Rasterize at the physical pixel size, then draw at logical size.
    const float raster = scale * fb_scale;
    fonts[static_cast<int>(Font::sans)] =
        add_text_font(io, inter_regular_compressed_data_base85, sans_size * raster);
    merge_icons(io, icon_size * raster);
    fonts[static_cast<int>(Font::sans_bold)] =
        add_text_font(io, inter_semibold_compressed_data_base85, sans_size * raster);
    merge_icons(io, icon_size * raster);
    fonts[static_cast<int>(Font::mono)] =
        add_text_font(io, iosevka_term_regular_compressed_data_base85, mono_size * raster);
    merge_icons(io, icon_size * raster);
    fonts[static_cast<int>(Font::title)] =
        add_text_font(io, inter_semibold_compressed_data_base85, title_size * raster);
    merge_icons(io, title_size * 0.85F * raster);
    fonts[static_cast<int>(Font::caption)] =
        add_text_font(io, inter_regular_compressed_data_base85, caption_size * raster);
    merge_icons(io, caption_size * raster);
    io.FontDefault = fonts[static_cast<int>(Font::sans)];
    io.FontGlobalScale = 1.0F / fb_scale;
    io.Fonts->Build();
    if (!first) {
        ImGui_ImplOpenGL3_DestroyFontsTexture();
        ImGui_ImplOpenGL3_CreateFontsTexture();
    }

    apply_theme(scale);
    applied_os_scale = os_scale;
    applied_framebuffer_scale = fb_scale;
    applied_user_scale = user;
    current_scale = scale;
    return true;
}

} // namespace rwsman::ui
