#!/usr/bin/env python3
"""Regenerates the embedded UI fonts and icon header under app/ui/.

The GUI embeds three subsetted, compressed fonts so the build never downloads
or depends on system fonts:

  * IBM Plex Sans (Regular, SemiBold) - chrome text        (SIL OFL 1.1)
  * IBM Plex Mono (Regular)            - IDs, offsets, values (SIL OFL 1.1)
  * Lucide icon font                   - toolbar/tree glyphs (ISC)

Inputs (put them in one directory, see app/ui/fonts/LICENSES.md for sources):
  IBMPlexSans-Regular.ttf  IBMPlexSans-SemiBold.ttf  IBMPlexMono-Regular.ttf
  lucide.ttf               IconsLucide.h

Requires: fonttools (`pip install fonttools`) and a C++ compiler. ImGui's
binary_to_compressed_c.cpp is compiled from an ImGui source checkout.

  tools/generate_ui_fonts.py --sources DIR --imgui build/_deps/imgui-src
"""
import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

# Lucide icons used by the GUI. Add a name here and rerun to make it available
# as ICON_LC_<NAME> in app/ui/icons.hpp.
ICONS = """
folder-open file save search chevron-left chevron-right chevron-down chevron-up
copy pin pin-off lock lock-open eye eye-off layers ruler scissors scan maximize
minimize camera terminal triangle-alert circle-alert circle-check info x settings
refresh-cw arrow-left arrow-right box cuboid users user map-pin route lightbulb
sparkles file-code braces database film play pause skip-back skip-forward image
crosshair hash binary list filter download external-link house trash circle-dot
diamond square triangle target move-3d mouse-pointer grid-3x3 sun moon panel-left
panel-right panel-bottom layout-dashboard bug flag link undo-2 redo-2 plus minus
check ellipsis dot folder package globe mountain component bookmark keyboard
command
""".split()

# Text ranges kept from the Plex families: Latin, punctuation, arrows, shapes.
TEXT_UNICODES = (
    "U+0020-007E,U+00A0-00FF,U+0100-017F,U+2010-2027,U+2030-203A,U+20AC,"
    "U+2190-2193,U+2212,U+2264-2265,U+25A0-25CF,U+2713-2714,U+2022,U+00B7"
)

FONTS = [
    ("IBMPlexSans-Regular.ttf", "plex_sans_regular", True),
    ("IBMPlexSans-SemiBold.ttf", "plex_sans_semibold", True),
    ("IBMPlexMono-Regular.ttf", "plex_mono_regular", True),
]


def run(*args):
    subprocess.run([str(a) for a in args], check=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--sources", required=True, type=Path)
    parser.add_argument("--imgui", required=True, type=Path)
    parser.add_argument("--out", type=Path, default=Path(__file__).resolve().parents[1] / "app" / "ui")
    args = parser.parse_args()
    fonts_dir = args.out / "fonts"
    fonts_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        tool = tmp / "binary_to_compressed_c"
        run("c++", "-O1", "-o", tool, args.imgui / "misc/fonts/binary_to_compressed_c.cpp")

        def embed(ttf: Path, symbol: str):
            out = subprocess.run([str(tool), "-base85", str(ttf), symbol], check=True,
                                 capture_output=True, text=True).stdout
            path = fonts_dir / f"{symbol}.inc"
            path.write_text(out)
            print(f"{path.name}: {ttf.stat().st_size} -> {len(out)} bytes of source")

        for name, symbol, _ in FONTS:
            subset = tmp / f"{symbol}.ttf"
            run(sys.executable, "-m", "fontTools.subset", args.sources / name,
                f"--unicodes={TEXT_UNICODES}", "--layout-features=kern,liga", "--no-hinting",
                f"--output-file={subset}")
            embed(subset, symbol)

        header = (args.sources / "IconsLucide.h").read_text()
        table = {m.group(1): int(m.group(2), 16) for m in re.finditer(
            r'#define ICON_LC_([A-Z0-9_]+) "[^"]*"\s*// U\+([0-9a-fA-F]+)', header)}
        chosen = []
        for icon in ICONS:
            key = icon.upper().replace("-", "_")
            if key not in table:
                sys.exit(f"unknown Lucide icon: {icon}")
            chosen.append((key, table[key]))
        unicodes = ",".join(f"U+{cp:04X}" for _, cp in chosen)
        subset = tmp / "lucide.ttf"
        run(sys.executable, "-m", "fontTools.subset", args.sources / "lucide.ttf",
            f"--unicodes={unicodes}", "--no-hinting", f"--output-file={subset}")
        embed(subset, "lucide_subset")

        lines = ["#pragma once", "",
                 "// Generated by tools/generate_ui_fonts.py from Lucide (ISC). Do not edit.", "",
                 "namespace rwsman::ui::icons {", ""]
        for key, cp in sorted(chosen):
            utf8 = chr(cp).encode("utf-8")
            escaped = "".join(f"\\x{b:02x}" for b in utf8)
            lines.append(f'inline constexpr const char* LC_{key} = "{escaped}"; // U+{cp:04X}')
        cps = sorted({cp for _, cp in chosen})
        lines += ["", "// Glyph ranges (pairs, zero-terminated) for ImGui font merging.",
                  "inline constexpr unsigned short glyph_ranges[] = {"]
        lines += [f"    0x{cp:04X}, 0x{cp:04X}," for cp in cps]
        lines += ["    0};", "", "} // namespace rwsman::ui::icons", ""]
        (args.out / "icons.hpp").write_text("\n".join(lines))
        print(f"icons.hpp: {len(chosen)} icons")


if __name__ == "__main__":
    main()
