#!/usr/bin/env python3
"""Generate src/csf_script_signatures.cpp from the shipped GSC/CSC programs.

Usage: tools/generate_script_signatures.py <unpacked-resource-root> [output.cpp]

Every instruction in .ACCIONES/.CONDICIONES is a group whose first child is the
opcode string; every operand group starts with its tag string. For each head
and role (instruction or operand) the table records the observed argument
counts and, per argument position, the shapes seen there: an operand tag, or
int/real/string/group/array for plain values. Identical files are counted once.
The editor uses the table only to warn about script text that differs from
everything the shipped game data contains.
"""

import collections
import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools" / "csffbs"))
import csffbs  # noqa: E402


def main() -> int:
    if len(sys.argv) not in (2, 3):
        print(__doc__.strip().splitlines()[2], file=sys.stderr)
        return 2
    root = Path(sys.argv[1])
    output = Path(sys.argv[2]) if len(sys.argv) == 3 else (
        Path(__file__).resolve().parent.parent / "src" / "csf_script_signatures.cpp")

    signatures = collections.defaultdict(
        lambda: {"arity": set(), "positions": collections.defaultdict(set), "count": 0})
    seen = set()
    files = 0
    for path in sorted(root.rglob("*")):
        if path.suffix.lower() not in (".gsc", ".csc") or not path.is_file():
            continue
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if digest in seen:
            continue
        seen.add(digest)
        files += 1
        document = csffbs.Document.load(str(path))
        entries = document.entries

        def label(node):
            if node.identifier_index is None:
                return ""
            return document.identifiers[node.identifier_index].data.rstrip(b"\0").decode("latin1")

        def string_value(node):
            entry = entries[node.entry_index]
            if entry.raw_type != 5:
                return None
            return document.strings[entry.raw_value_or_size].data.rstrip(b"\0").decode("latin1")

        def head(node):
            entry = entries[node.entry_index]
            if entry.raw_type != 1 or not node.children:
                return None
            return string_value(node.children[0])

        def shape(node):
            tag = head(node)
            if tag is not None:
                return tag
            return {1: "group", 2: "array", 3: "int", 4: "real", 5: "string"}[
                entries[node.entry_index].raw_type]

        def record(role, node):
            tag = head(node)
            if tag is None:
                return
            signature = signatures[(tag, role)]
            signature["count"] += 1
            arguments = node.children[1:]
            signature["arity"].add(len(arguments))
            for index, argument in enumerate(arguments):
                signature["positions"][index].add(shape(argument))
                record("operand", argument)

        def walk(node):
            if label(node) in (".ACCIONES", ".CONDICIONES"):
                for instruction in node.children:
                    record("instruction", instruction)
                return
            for child in node.children:
                walk(child)

        for top in document.roots:
            walk(top)

    rows = []
    for (tag, role), signature in sorted(signatures.items()):
        maximum = max(signature["arity"])
        positions = ";".join("|".join(sorted(signature["positions"][i])) for i in range(maximum))
        rows.append(f'    {{"{tag}"sv, {"true" if role == "instruction" else "false"}, '
                    f'{min(signature["arity"])}, {maximum}, {signature["count"]}, "{positions}"sv}},')

    output.write_text(
        "// Generated by tools/generate_script_signatures.py from "
        f"{files} distinct shipped GSC/CSC files.\n"
        "// Do not edit by hand; rerun the generator instead.\n"
        '#include "csf/script_signatures.hpp"\n\n'
        "namespace csf {\nnamespace {\n\nusing namespace std::string_view_literals;\n\n"
        "// clang-format off\nconstexpr ScriptSignature table[]{\n" + "\n".join(rows) +
        "\n};\n// clang-format on\n\n} // namespace\n\n"
        "std::span<const ScriptSignature> script_signatures() noexcept { return table; }\n\n"
        "} // namespace csf\n",
        encoding="utf-8", newline="\n")
    print(f"{output}: {len(rows)} signatures from {files} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
